export const metadata = {
  title: 'Home | Next Movies',
  description: 'Generated by Next.js',
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <div>
      {children}
      다른 Layout을 만들어보자
    </div>
  );
}
